name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          configuration: phpunit.xml
          args: --coverage-clover=coverage.xml
        env:
          XDEBUG_MODE: coverage
      - uses: codecov/codecov-action@v2.1.0
