name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v9
        with:
          configuration: phpunit.xml
          args: --coverage-text
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
